import fs from 'node:fs/promises';
import {blocks} from '../authoring/blocks.mjs';
const settings=JSON.parse(await fs.readFile('authoring/settings.json','utf8'));
const original=JSON.parse(await fs.readFile('authoring/original-course.json','utf8'));
let privateOriginal;try{privateOriginal=JSON.parse(await fs.readFile('private/original-course.json','utf8'));}catch{ /* optional existing notes */ }
const version=settings.contentVersion;
const sourceNames={
 'kim-2027-pdf':'КИМ 09.02.07-3-2027, т. 1, с. 7, 12–14, 33–37',
 'kim-2027-zip':'Приложение к образцу КИМ 09.02.07-3-2027',
 'kim-style-guide':'Руководство по стилю из приложения КИМ, с. 1',
 'pirip-01-site':'ПИРИП-01: HTML, CSS, JavaScript',
 'pirip-02-site':'ПИРИП-02: UX и прототипирование',
 'lit-markin-baranov-2026':'Маркин А. В., Баранов А. Ю. Web-программирование. 2026',
 'lit-adams-floyd-2025':'Адамс Д. Р., Флойд К. С. Основы работы с XHTML и CSS. 2025',
 'wcag-22':'W3C: WCAG 2.2', 'mdn-javascript':'MDN: JavaScript и Fetch API',
 'ecma-262':'ECMA-262: текущая спецификация ECMAScript'
};
const literature={primary:[
 {citation:'Маркин, А. В., Баранов, А. Ю. Web-программирование. 3-е изд. 2026',url:'https://www.iprbookshop.ru/books/163055/details'},
 {citation:'Адамс, Д. Р., Флойд, К. С. Основы работы с XHTML и CSS. 4-е изд. 2025',url:'https://www.iprbookshop.ru/books/146372/details'}
],additional:[{citation:'Богданова, С. В. Технологии программирования. Ч. 2. 2024',url:'https://www.iprbookshop.ru/books/156618/details'}]};
const course={schemaVersion:1,contentVersion:version,id:'pirip-2027',code:'ПИРИП',discipline:'Проектирование и разработка интерфейсов пользователя',year:settings.year,
 heroTitle:'Проектируем интерфейсы.',heroAccent:'Доказываем результат.',slogan:'От требований КИМ к понятному и работающему приложению.',
 mascot:'brand/rhino-designer.webp',mascotAlt:'Носорог-проектировщик интерфейсов',logo:'brand/synergy-logo.png',ornament:'brand/side-ornament.webp',font:'fonts/raleway-cyrillic.woff2',topicArrow:'brand/topic-arrow.webp',
 materialsUrl:'https://disk.yandex.ru/d/doO6apAunlrARw',literature,assessment:{mode:'autonomous',url:'assessment.json'},demo:false,semesters:[settings.semester],lectures:[],glossary:[],curriculum:[]};
const bank={schemaVersion:1,courseId:course.id,contentVersion:version,mode:'autonomous-educational',notice:'Учебная автономная самопроверка. Ключи доступны в файле сайта; результат не является оценкой ДЭ.',keys:{}};
const pack={schemaVersion:1,courseId:course.id,contentVersion:version,notes:{}};
const migration=[];const registry=[];const corrections=[];const questionMap=[];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const list=xs=>'<ul>'+xs.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>';
const source=ids=>(ids||[]).map(x=>sourceNames[x]||x).join('; ');
const correction=(p,text)=>corrections.push({slide:p.id,change:text});
function correctPoint(p,li){
 p=structuredClone(p);
 if(p.id==='minimum-stack') {p.title='Полный стек обязателен; PHP — учебный выбор';p.cards=[{label:'Frontend',value:'Интерфейс и клиентское поведение'},{label:'Backend',value:'ООП и обработка правил; в курсе — PHP'},{label:'Данные',value:'БД и ER-диаграмма; в курсе — MySQL'},{label:'Инструменты',value:'Доступные на площадке библиотеки и фреймворки'}];correction(p,'PHP/MySQL обозначены как учебный стек, не единственная норма КИМ.');}
 if(p.id==='git-offline') {p.compare.left=['Локальные библиотеки площадки','Офлайн-справочник','Проверка подключения к БД','Подготовительный день — без проектирования и кода'];correction(p,'Удалена рекомендация заранее готовить экзаменационный шаблон; уточнены границы подготовительного дня.');}
 if(p.id==='time-210') {p.steps=[{title:'0–90 минут',text:'Задание 1: приложение, БД и роли'},{title:'90–150 минут',text:'Задание 2: дизайн, карточки, фильтрация, 390×844'},{title:'150–210 минут',text:'Задание 3: интеграция, интерактивность и качество'},{title:'Внутри задания 3',text:'Учебный резерв: последние 15 минут на проверку и сохранение'}];correction(p,'Восстановлены 90/60/60 минут; резерв явно включён в задание 3.');}
 if(p.id==='strategy') {p.compare.right=['Обязательные доработки по заданиям 2 и 3','Фильтр и карточки — задание 2','Анимации и интеграция — задание 3','Полировка после выполнения требований'];p.compare.rightTitle='Дальнейшие обязательные этапы';correction(p,'Фильтр и анимация больше не названы необязательными улучшениями.');}
 if(p.id==='seed-data') {p.bullets=['Администратор создаётся с хешем пароля','Тестовые пользователи явно помечены','Обычный INSERT не идемпотентен: повтор требует отдельного решения'];correction(p,'Исправлено необоснованное обещание безопасного повторного запуска seed.sql.');}
 if(p.id==='registration-validation') p.steps[0].text='Нормализовать логин и телефон по принятой политике; пароль не изменять';
 if(p.id==='reviews-table') p.bullets[0]='reservation_id — UNIQUE в учебной модели с одним отзывом';
 if(p.id==='review-rule') p.steps[2].text='В учебной модели: один отзыв, UNIQUE и обработка конфликта';
 if(p.id==='status-transition') p.subtitle='Переходы и коды HTTP — авторская реализация; КИМ задаёт пользовательские статусы.';
 if(p.id==='points-map') p.subtitle='Задание 1: 6 + 16 + 3; задание 2: 11 + 10 + 4; задание 3: 15 + 10. Таблица 7 КИМ, с. 13.';
 if(p.id==='training-domain') p.subtitle='Портал бронирования помещений: предметная область образца, не гарантия окончательного варианта.';
 if(p.id==='task2-minimum') p.compare.right[0]='Слайдер не указан в данном образце';
 if(p.id==='kim-media') {p.title='Медиа приложения: происхождение и назначение';p.bullets=['22 медиафайла в каждом проверенном наборе','3 файла social в каждом наборе','Вложенные ZIP для ПА и БУ совпадают по SHA-256','PT Sans указан руководством; наличие Inter не отменяет это требование'];}
 if(p.id==='dom-budget') {p.title='DOM и перерисовки проверяют измерениями';p.compare.right.push('Оптимизировать по результатам измерения');}
 if(li===1 && ['users-table','reservations-table','er-keys'].includes(p.id)) p.subtitle='Учебная модель. Фрагмент описывает структуру; это не полный исполняемый SQL-скрипт.';
 return p;
}
function visibleText(s){return [s.body,...(s.bullets||[]),s.notebook,...(s.references||[]).map(x=>x.citation),...(s.visual?.items||[]).map(x=>x.title+': '+x.text),...(s.visual?.parts||[]).map(x=>x.label+': '+x.explanation),...(s.visual?.rows||[]).map(x=>x.join(' — ')),s.visual?.caption].filter(Boolean).join(' ');}
const rotate=(xs,n)=>[...xs.slice(n%xs.length),...xs.slice(0,n%xs.length)];
for(let li=0;li<5;li++){
 const old=original.lectures[li],prefix='L'+String(li+1).padStart(3,'0');
 const lecture={id:old.id,title:old.title,sourceTitle:old.title,semester:settings.semester,question:old.description,slides:[]};
 const add=(s,context={})=>{lecture.slides.push(s);const text=visibleText(s);const specific=context.script||text||s.title;
 const answer=s.task?bank.keys[s.task.id]?.explanation||'':context.answer||'';
 pack.notes[s.id]={script:specific,preparation:context.preparation||s.source||'Подготовить текущий слайд и проверить читаемость на экране.',notebook:s.notebook||context.notebook||'Запись не требуется; чтение и обсуждение текущего материала.',questions:context.questions||'',answer,estimatedSeconds:context.seconds||(s.task? (s.task.type==='matching'?110:70):s.visual?85:s.kind==='section'?20:s.kind==='notebook'?80:s.kind==='theory'?95:50)};
 return s;
 };
 add({id:prefix+'-title',kind:'title',title:old.title,kicker:'ПИРИП · Подготовка к ДЭ 2027',body:old.description},{script:old.description+' Сегодня пройдём пять вопросов: '+blocks[li].map(x=>x.title).join('; ')+'. '+old.objectives.join(' '),preparation:'Исходные знания: основы HTML/CSS и пользовательских сценариев; для кода — базовый JavaScript, SQL и серверные запросы. '+settings.rpdStatus+' '+settings.semesterStatus,seconds:60});
 add({id:prefix+'-literature-primary',kind:'literature',title:'Основная литература',kicker:'Источники',readingGroup:'primary'},{script:'Для этой темы сохранены две книги исходного курса. Web-программирование помогает связать интерфейс с обработкой данных, а книга по XHTML и CSS — разобрать структуру и оформление веб-страниц. Издание по XHTML читаем с учётом исторического контекста; актуальные API сверяем с документацией. Конкретные страницы книг не заданы и не приписываются источникам.',seconds:40});
 add({id:prefix+'-literature-additional',kind:'literature',title:'Дополнительная литература',kicker:'Источники',readingGroup:'additional'},{script:'В дополнительном списке сохранена книга Богдановой «Технологии программирования», часть 2. Она служит источником для самостоятельного повторения общих принципов программирования. Требования демоэкзамена сверяем по КИМ и двум переданным методическим рекомендациям, а не выводим из учебника. Далее откроем материалы занятия.',seconds:30});
 add({id:prefix+'-materials',kind:'materials',title:'Материалы занятия',kicker:'Ссылка и QR-код',body:'Откройте папку материалов курса. Сохранённые лабораторные доступны по ссылке в перечне источников в конце лекции.'},{script:'На слайде сохранён адрес папки материалов исходного курса. QR-код и текстовая ссылка ведут по одному адресу. Состав папки здесь не перечисляется: открыть ссылку нужно перед занятием и выбрать выданные преподавателем материалы. Сохранённые лабораторные доступны также в источниках в конце этой лекции.',seconds:35});
 add({id:prefix+'-agenda',kind:'agenda',title:'Вопросы темы',kicker:'Карта темы'},{script:'Маршрут построен последовательно: '+blocks[li].map((b,i)=>`${i+1}. ${b.title}`).join('; ')+'. Первые вопросы вводят понятия, следующие связывают их с работой приложения, а заключительный помогает проверить результат. После каждого вопроса будут четыре задания: выбор одного, нескольких ответов, краткий ввод и соответствие.',seconds:50});
 add({id:prefix+'-objectives-plan',kind:'theory',title:'Что научимся делать',kicker:'Результаты занятия',bullets:old.objectives},{script:old.objectives.join(' ')+' Для каждого результата будем искать действие и наблюдаемый итог, чтобы отличать знакомство с термином от способности применить его в задании.',seconds:60});
 add({id:prefix+'-context',kind:'theory',title:'Учебный кейс и границы',kicker:'Перед началом',body:'«Конференции.РФ» — предметная область образца КИМ. Четыре таблицы, PHP/MySQL, дополнительные проверки и короткий показ — учебные решения курса. Состав заданий, исходный функционал и 390×844 взяты из переданных документов. Полнота покрытия рабочей программы дисциплины не подтверждена: РПД не предоставлена.'},{seconds:60});
 for(let qi=0;qi<5;qi++){
  const block=blocks[li][qi],q=prefix+'-Q'+String(qi+1).padStart(2,'0');
  const src=(li===0||li===4?'КИМ, с. 7, 12–14, 33–37; методические рекомендации для обучающихся, с. 1–4; для СПО, с. 1–2. ':'')+'Авторское объяснение и учебный пример на основе источников лекции.';
  add({id:q+'-section',kind:'section',title:block.title,kicker:'Вопрос '+String(qi+1).padStart(2,'0'),body:block.rule},{script:'Переходим к вопросу «'+block.title+'». '+block.theory+' В конце вопроса проверим правило: '+block.rule,seconds:25});
  const theory=add({id:q+'-meaning',kind:'theory',title:'Как это работает',kicker:block.title,body:block.theory,source:src},{script:block.theory+' '+block.example[0]+' Этот пример разберём после основных понятий.',questions:'Почему важно это правило? '+block.rule+'\nЧто произойдёт при нарушении? '+block.error[1],seconds:105});
  const terms=add({id:q+'-terms',kind:'theory',title:'Понятия вопроса',kicker:block.title,bullets:block.terms.map(([term,def])=>term+' — '+def),source:src},{script:block.terms.map(([term,def])=>term+': '+def).join(' ')+' Важно различать эти понятия по функции в рассматриваемом сценарии. '+block.rule,questions:'Как связаны понятия с примером? '+block.example[0]+' '+block.example[3],seconds:100});
  for(const [term,definition] of block.terms){const existing=course.glossary.find(x=>x.term===term&&x.definition===definition);if(existing)existing.slideIds.push(terms.id);else course.glossary.push({term,definition,slideIds:[terms.id]});}
  const originals=[];
  for(let pi=qi*4;pi<qi*4+4;pi++){
   const p=correctPoint(old.content[pi],li),id=prefix+'-'+p.id;
   const s={id,kind:p.type==='mistake'?'warning':p.type==='case'||p.code?'example':'theory',title:p.title,kicker:p.eyebrow||block.title,source:source(p.sourceIds)};
   if(p.subtitle||p.quote)s.body=[p.subtitle,p.quote].filter(Boolean).join(' ');
   if(p.bullets)s.bullets=p.bullets;
   if(p.code){s.visual={type:'codeParts',parts:[{code:p.code,label:'Учебный фрагмент',explanation:'Фрагмент рассматривается в контексте: '+p.title+'. Это схема или сокращённый пример, требующий окружения приложения.'}],caption:p.title+'. Схема или сокращённый учебный код; самостоятельный запуск без окружения не предполагается.'};}
   else if(p.steps)s.visual={type:p.type==='architecture'?'layers':'process',items:p.steps,caption:p.title+'. '+(p.id==='time-210'?'90/60/60 минут — по методическим рекомендациям; резерв — учебный.':'Читать по порядку элементов и сопоставлять с результатом действия.')};
   else if(p.compare)s.visual={type:'comparison',columns:[p.compare.leftTitle,p.compare.rightTitle],rows:Array.from({length:Math.max(p.compare.left.length,p.compare.right.length)},(_,i)=>[p.compare.left[i]||'—',p.compare.right[i]||'—']),caption:p.title+'. Сопоставьте назначения и ограничения двух вариантов.'};
   else if(p.cards)s.visual={type:'matrix',columns:['Элемент','Назначение или условие'],rows:p.cards.map(x=>[x.label,x.value]),caption:p.title+'. Таблица связывает каждый элемент с его назначением.'};
   if(p.media){s.image={src:'data:image/jpeg;base64,'+(await fs.readFile('public'+p.media)).toString('base64'),alt:p.mediaAlt,caption:'Из предоставленного приложения КИМ. Назначение: '+p.title};}
   if(s.visual&&s.bullets?.length>3&&s.visual.type==='codeParts'){s.body=[s.body,...s.bullets].filter(Boolean).join(' ');delete s.bullets;}
   const relatedIds=[];
   if((s.visual||s.image)&&(s.body||s.bullets)){
    const explanationId=id+'-context';
    add({id:explanationId,kind:'theory',title:p.title,kicker:'Условия и пояснения',...(s.body?{body:s.body}:{}),...(s.bullets?{bullets:s.bullets}:{}),source:s.source},{script:[s.body,...(s.bullets||[])].filter(Boolean).join(' '),seconds:80});
    relatedIds.push(explanationId);originals.push(explanationId);delete s.body;delete s.bullets;
   }
   const originalNote=privateOriginal?.lectures[li].content[pi].teacherNote||'';
   const raw=[p.subtitle,p.quote,...(p.bullets||[]),...(p.cards||[]).map(x=>x.label+' — '+x.value),...(p.steps||[]).map(x=>x.title+': '+x.text),p.compare?`${p.compare.leftTitle}: ${p.compare.left.join('; ')}. ${p.compare.rightTitle}: ${p.compare.right.join('; ')}`:''].filter(Boolean).join(' ');
   const codeExplain=p.code?'В примере показан следующий фрагмент: '+p.code+'. '+(p.bullets?.join(' ')||'Он иллюстрирует структуру данных или последовательность операций, а не готовое приложение. Требуемое окружение и проверки рассматриваются в текущем вопросе.') : '';
   add(s,{script:'На этом шаге рассматриваем: '+p.title+'. '+raw+' '+codeExplain,preparation:source(p.sourceIds)+(originalNote?'\nСохранённая авторская заметка: '+originalNote:''),questions:p.check? p.check.question+' '+p.check.answer+'. '+p.check.explanation:'',seconds:p.code?100:s.visual?85:70});
   migration.push({source:`src/data/lectures/lecture${String(li+1).padStart(2,'0')}.ts`,sourceId:p.id,lectureId:old.id,slideIds:[...relatedIds,id],change:'Перенос всех ученических полей в модель общего движка; заметки отделены; пояснения перед сложной графикой вынесены отдельно.'});originals.push(id);
  }
  const example=add({id:q+'-example',kind:'example',title:'Разобранный пример',kicker:block.title,visual:{type:'process',items:block.example.map((text,i)=>({title:['Исходные данные','Действие','Проверка','Результат'][i],text})),caption:'Учебный пример. '+block.rule},source:src},{script:block.example.join(' ')+' Полученный результат объясняется правилом: '+block.rule,seconds:150,questions:'Что изменится, если нарушить условие? '+block.error[1]+'\nКак проверить результат? '+block.example[3]});
  const diagnostic=add({id:q+'-diagnostic',kind:'theory',title:'Причина, последствие, исправление',kicker:block.title,visual:{type:'cause',cause:block.error[0],effect:block.error[1],solution:block.error[2],caption:'Читайте от причины к последствию, затем к действию, устраняющему причину.'},source:src},{script:'Причина рассматриваемой ошибки: '+block.error[0]+' Поэтому '+block.error[1]+' Исправление направлено на причину: '+block.error[2]+' После него повторяем тот же сценарий, который обнаружил проблему.',seconds:95});
  add({id:q+'-warning',kind:'warning',title:'Ошибка и граница применения',kicker:block.title,body:block.error[0]+' '+block.error[1],bullets:[block.error[2],block.rule],source:src},{script:block.error.join(' ')+' Запомним границу: '+block.rule,seconds:75});
  add({id:q+'-notebook',kind:'notebook',title:'Запишите',kicker:block.title,notebook:block.rule,source:src},{script:'Зафиксируем правило своими словами и сверим с формулировкой на слайде. '+block.rule+' Оно опирается на уже разобранный пример: '+block.example[3],seconds:80});
  const taskIds=[];
  const makeTask=(type,n,prompt,extra,key)=>{const id=q+'-T0'+n;const task={id,type,prompt,...extra};bank.keys[id]={type,...key};taskIds.push(id);add({id:id+'-slide',kind:'test',title:['Один ответ','Несколько ответов','Краткий ввод','Соответствие'][n-1],kicker:block.title,task},{script:'Самостоятельная проверка вопроса «'+block.title+'». '+prompt+' Сначала сформулируйте основание решения, затем отправьте ответ. Проверка использует понятия и примеры только этого вопроса.',questions:'Что делать при затруднении? Вернуться к определениям '+terms.id+' и примеру '+example.id+'.',answer:key.explanation});};
  const options=rotate(block.quiz.slice(1).map((text,i)=>({id:'o'+(i+1),text})),qi+li);
  makeTask('single',1,block.quiz[0],{options},{correct:['o1'],explanation:block.quiz[1]+'. '+block.rule,optionExplanations:Object.fromEntries(options.map(o=>[o.id,o.id==='o1'?'Соответствует условию: '+block.rule:'Этот вариант не обозначает требуемое действие или условие. В вопросе требуется: '+block.quiz[1]+'.']))});
  const t=block.terms;
  const statements=[{id:'m1',text:t[0][0]+' — '+t[0][1]},{id:'m2',text:t[1][0]+' — '+t[1][1]},{id:'m3',text:t[2][0]+' — '+t[3][1]},{id:'m4',text:t[3][0]+' — '+t[2][1]},{id:'m5',text:t[0][0]+' — '+t[1][1]}];
  const explanations=Object.fromEntries(statements.map((x,i)=>[x.id,i<2?'Верно: '+x.text:'Определения перепутаны. '+t[i===2?2:i===3?3:0].join(' — ')]));
  makeTask('multiple',2,'Выберите ровно два корректных определения из пяти.',{choose:2,options:rotate(statements,li+qi+1)},{correct:['m1','m2'],explanation:'Корректны определения: '+t[0].join(' — ')+' '+t[1].join(' — '),optionExplanations:explanations});
  makeTask('short',3,'Введите термин или обозначение из этого вопроса: '+t[2][1]+' Формат — как в перечне понятий; регистр и лишние пробелы не учитываются.',{}, {accepted:[t[2][0]],explanation:t[2].join(' — ')});
  makeTask('matching',4,'Сопоставьте четыре понятия с их определениями. Каждому понятию соответствует ровно одно определение.',{items:t.map(([text],i)=>({id:'i'+i,text})),options:rotate(t.map(([,text],i)=>({id:'d'+i,text})),(li+qi)%3+1)}, {pairs:Object.fromEntries(t.map((_,i)=>['i'+i,'d'+i])),explanation:t.map(x=>x.join(' — ')).join('\n')});
  questionMap.push({lectureId:old.id,questionId:q,title:block.title,source:src,explanationSlideIds:[theory.id,terms.id,...originals,example.id,diagnostic.id],taskIds});
  course.curriculum.push({topic:old.title+' / '+block.title,outcome:block.rule,source:'Учебная карта подготовки по КИМ; не утверждённая РПД. '+src,slideIds:[theory.id,terms.id,...originals,example.id],taskIds});
 }
 add({id:prefix+'-final',kind:'summary',title:'Итоги и связь с практикой',kicker:'Обобщение',bullets:old.finalChecklist},{script:old.finalChecklist.join(' ')+' Сохранённая лабораторная работа: '+old.laboratoryId+'. Её 180 минут являются исходной методической рекомендацией, а не часами РПД.',questions:old.selfCheck.prompt,answer:Array.isArray(old.selfCheck.answer)?old.selfCheck.answer.join('; ')+'. '+old.selfCheck.explanation:old.selfCheck.answer+'. '+old.selfCheck.explanation,seconds:100});
 add({id:prefix+'-sources',kind:'literature',title:'Источники и лабораторные',kicker:'Для самостоятельной работы',readingGroup:'additional',references:[{citation:'КИМ 09.02.07-3-2027, т. 1: с. 7, 12–14, 33–37. Переданный PDF.'},{citation:'Методические рекомендации для обучающихся и представителей СПО, 09.02.07-3-2027: с. 1–4. Переданные PDF.'},{citation:'Пять лабораторных работ исходного курса',url:'https://olgakraven.github.io/2026-PIRIP-lecture/laboratories.html'}]},{script:'Требования сверены с переданным КИМ и двумя методическими рекомендациями. В случаях расхождения сохраняем приоритет КИМ и называем различие в отчёте. По ссылке доступны пять сохранённых лабораторных с шагами и критериями учебной приёмки. Они не являются экзаменационным регламентом.',seconds:50});
 add({id:prefix+'-questions',kind:'questions',title:'Вопросы от аудитории',kicker:'Обсуждение',bullets:['Какое правило этой темы вы сможете проверить действием?','Где проходит граница между требованием КИМ и учебным решением?','Какой отрицательный сценарий обнаружит ошибку раньше?']},{script:'Вернёмся к результатам занятия. '+old.objectives.join(' ')+' Выберите один пример и назовите исходные данные, действие и ожидаемый результат. Для спорного требования обращаемся к указанной странице источника, а для авторского решения объясняем его условия.',questions:blocks[li].map(b=>b.quiz[0]+' '+b.quiz[1]+'. '+b.rule).join('\n'),seconds:150});
 for(let si=0;si<lecture.slides.length;si++){const s=lecture.slides[si],note=pack.notes[s.id];if(s.kind!=='title'&&s.kind!=='questions'){note.script=(si>0?'После «'+lecture.slides[si-1].title+'» '+note.script:'')+(lecture.slides[si+1]?' Далее: «'+lecture.slides[si+1].title+'».':'');}if(!note.questions)note.questions='Как проверить понимание этого слайда? '+(s.notebook||s.visual?.caption||s.body||s.title);}
 registry.push({id:lecture.id,title:lecture.title,slides:lecture.slides.length,questions:5,tasks:20,visuals:lecture.slides.filter(s=>s.visual).length,estimatedMinutes:Math.round(lecture.slides.reduce((n,s)=>n+pack.notes[s.id].estimatedSeconds,0)/60),officialHours:null,status:'Содержание собрано; требуется проверка сборки и PDF'});
 course.lectures.push(lecture);
 for(const oldId of ['title','objectives-plan','self-check','sources','final'])migration.push({source:'app/course.ts::buildDeck',sourceId:oldId,lectureId:old.id,slideIds:[prefix+'-'+(oldId==='self-check'?'final':oldId)],change:oldId==='self-check'?'Исходная итоговая самопроверка сохранена в приватном сопровождении итогового слайда; обязательные четыре типа добавлены по вопросам.':'Служебный слайд перенесён; источники разделены на литературу и материалы.'});
}
for(const d of ['private','reports'])await fs.mkdir(d,{recursive:true});
for(const [file,data] of [['public/course.json',course],['public/assessment.json',bank],['private/teacher-pack.json',pack],['reports/migration-map.json',migration],['reports/lecture-register.json',registry],['reports/question-map.json',questionMap],['reports/corrections.json',corrections]])await fs.writeFile(file,JSON.stringify(data,null,2)+'\n');
await fs.writeFile('private/teacher.md','# ПИРИП · Сценарий преподавателя\n\nВерсия: '+version+'\n\n'+course.lectures.map(l=>'## '+l.title+'\n\n'+l.slides.map(s=>'### '+s.id+' · '+s.title+'\n\n'+Object.entries(pack.notes[s.id]).map(([k,v])=>'**'+k+'**\n\n'+v).join('\n\n')).join('\n\n')).join('\n\n'));
await fs.writeFile('private/preparation.md','# Подготовка к занятиям\n\n'+settings.rpdStatus+'\n\n'+settings.semesterStatus+'\n\n'+registry.map((l,i)=>'## '+l.title+'\n\nРасчётный полный маршрут: '+l.estimatedMinutes+' минут. Исходные 90 минут не покрывают расширенный маршрут; требуется распределение на занятия по программе.\n\n'+blocks[i].map(b=>'- '+b.title+': '+b.rule).join('\n')+'\n\nПредварительно открыть КИМ, подготовить локальные учебные данные, проверить импорт TeacherPack, два окна и PDF. PHP/SQL-фрагменты в слайдах не являются протестированным самостоятельным приложением.').join('\n\n'));
await fs.writeFile('reports/progress.json',JSON.stringify({contentVersion:version,templateCommit:settings.templateCommit,stages:{inventory:'проверено',sources:'проверено',content:'собрано',teacher:'собрано',build:'запланировано',browser:'запланировано',pdf:'запланировано',publication:'запланировано'},limitations:[settings.rpdStatus,settings.semesterStatus,'Официальные часы и данные преподавателя не заданы.','Полный расширенный маршрут не укладывается в прежние 90 минут; хронометраж рассчитан отдельно.']},null,2));
// Keep the pre-existing labs available as a supplementary document; no new labs are created.
const labBody=original.laboratories.map(l=>'<section id="'+l.id+'"><h2>'+esc(l.order+'. '+l.title)+'</h2><p>'+esc(l.goal)+'</p><p>Учебная рекомендация: '+l.recommendedDurationMinutes+' минут. '+(l.order===5?'Для экзаменационного БУ задания распределены 90/60/60 минут; тренировка 180 минут не имитирует полный регламент.':'')+'</p><h3>Исходные файлы</h3>'+list(l.starterFiles)+l.steps.map(s=>'<h3>'+esc(s.title)+'</h3>'+list(s.actions)+'<p><strong>Результат:</strong> '+esc(s.result)+'</p>'+list(s.files)).join('')+'<h3>Что сдаём</h3>'+list(l.deliverables)+'<h3>Учебная приёмка</h3>'+list(l.acceptanceCriteria)+'<h3>Проверки</h3>'+list(l.testCases.map(t=>t.action+' → '+t.expected))+'<h3>Типичные ошибки</h3>'+list(l.commonErrors)+'<h3>Восстановление</h3>'+list(l.recoveryHints)+'<h3>Передача результата</h3>'+list(l.submission)+'</section>').join('');
await fs.writeFile('public/laboratories.html','<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ПИРИП · Лабораторные работы</title><style>@font-face{font-family:Raleway;src:url(fonts/raleway-cyrillic.woff2)}body{font:18px/1.65 Raleway,Arial,sans-serif;color:#1c1c1c;margin:auto;padding:24px;max-width:960px}h1,h2{border-left:5px solid #ed131c;padding-left:16px}a{color:#4561c8}section{margin:64px 0}li{overflow-wrap:anywhere}@media print{nav{display:none}section{break-before:page}}</style><nav><a href="./">К лекциям</a></nav><h1>ПИРИП · Пять лабораторных работ</h1><p>Сохранённые задания исходного курса. Это учебная практика. Схема из четырёх таблиц, PHP/MySQL и правило одного отзыва — решения курса. В подготовительный день ДЭ код не пишут и БД не проектируют.</p>'+labBody+'</html>');
console.log(JSON.stringify({lectures:course.lectures.length,slides:course.lectures.flatMap(l=>l.slides).length,tasks:Object.keys(bank.keys).length,notes:Object.keys(pack.notes).length,registry},null,2));
